### ISSUE TITLE
Layout problem when moving screens

### ISSUE THREAD

**Issue by craigseymour** [Innofactor/XrmToolBox.PluginTraceViewer#2]
When I move the XrmToolBox from one screen to another, the right hand pane doesn't resize its panels.  So when going from (for example) portrait to landscape, the Exception panel mostly vanishes:

![exception_panel_gone](https://cloud.githubusercontent.com/assets/14763830/17528108/d9421c9e-5e65-11e6-974c-ffd87b281e00.png)

**Comment by rappen** [comment]
Is it not possible to drag the splitter between Message and Exception to adjust it manually?

**Comment by craigseymour** [comment]
Not when it goes off the bottom of the screen.  Perhaps an edge case, although it does happen when you go from windowed to full screen as well, so perhaps not?

![exception_panel_gone_3](https://cloud.githubusercontent.com/assets/14763830/17544759/1be5bc70-5ed1-11e6-8f80-5587b9aa84ca.png)

**Comment by rappen** [comment]
Fixed by commit https://github.com/Innofactor/XrmToolBox.PluginTraceViewer/commit/ad95060de2080ebceb671fa722f712f6eb8f9401
