### ISSUE TITLE
Plugin Trace Viewer - Date From and Date To cannot be changed to any other day

### ISSUE THREAD

**Issue by dtate22** [Innofactor/XrmToolBox.PluginTraceViewer#39]
I'm attempting to change the Date From and Date To for filtering on a different day but cannot change the values.

Please update.

Version 1.2017.1.21
![1](https://cloud.githubusercontent.com/assets/20981265/22825867/17907416-ef55-11e6-801a-cd82ecf23466.png)
![2](https://cloud.githubusercontent.com/assets/20981265/22825871/1a8070cc-ef55-11e6-80b1-08787af43950.png)

**Comment by rappen** [comment]
I am a bit uncertain what you mean with "Please update".
These fields get their max/min values from log records available in the database, there is no point in selecting a date for which there are no records.
If log records have been added since you started the tool, you can click the button *Refresh Filter Options" to reload the constraints for the different filters based on existing log records.

**Comment by dtate22** [comment]
I think there is a problem...
- I will continue to capture screenshots.
- I will say I thought about what you were saying and I gotta say the way you tool works in this instance is a little strange, but rather than complain.  I will take screenshots that include the date and time that way, we will be able to view it together in order for any future points to be made.

**Comment by rappen** [comment]
Please do!
I appreciate any feedback :)

**Comment by adner** [comment]
Hello Jonas! What is the behaviour when modifying the date constraints before any logs have been retrieved from the system? That is, if I open up a new Plugin Trace Viewer tab it would be nice to set any time contraint that I want, initially. Or are the available time constraints retrieved from the system even before I click "Retrieve Logs" the first time?

**Comment by rappen** [comment]
Hi - yes the constraints (dates, plugins, entities, messages) are retrieved when the tool is opened.
It is possible to reload these from the menu.

![image](https://cloud.githubusercontent.com/assets/2572253/24123609/807b904e-0dc0-11e7-8683-1d9faa98c0a3.png)
