### ISSUE TITLE
Expose RequestId in the column list

### ISSUE THREAD

**Issue by seanmcne** [Innofactor/XrmToolBox.PluginTraceViewer#50]
please expose 'requestid' and 'correlationid' columns in the returned list - thx!

**Comment by rappen** [comment]
The Correlation Id is exposed, although transposed to single letters (as reading GUIDs is rarely usable).
This is explaing in this blog post: http://jonasrapp.innofactor.se/2017/03/eXtremePluginDev-IV.html

I have looked at the Request Id, but actually never found it contain anything but Guid.Empty.
If you have scenarios where it is populated and could be used I would be thankful for information about this! :)

**Comment by seanmcne** [comment]
@rappen 
The correlation ID is very useful when troubleshooting when there is more than a single depth - having easier access to see the actual guid (in a field or maybe even raw in the list) could help when interacting with support.  For requestId, you should always see this for Sync plugins in CRM Online when a 'request' originates from a front end server (like orgservice, webapi, end user request like a form save, etc). 

One relevant example of it's use, even when you're not working with a Premier Field Engineer or Support is: when you execute an "UpdateRequest" (or anything that inherits from OrganizationRequest) there's a 'requested' property.  This property is guid.empty by default, however if you set this to a random Guid (Guid.NewGuid()) and log it you'll find this very same guid appear in your plugin trace logs in CRM Online.  

A real world example of the above is: 
- You've created an app that creates records in CRM
- Every single organizationRequest you send out you're setting Guid.NewGuid() and logging that requested, what type of request, and how long it takes to respond. 
- You notice a pattern where a certain type of request is slow
- You can use those RequestId's to correlate to your logs
- After investigation you cannot find the issue and open a support request 
- Within several days support can also take the RequestId (even if it didn't fire a plugin) and sometimes gain insight into what exactly happened. If you do not generate a request Id for requests they will be randomly generated server side (and you won't get a response with that ID today). 


_Note: RequestId will be blank if the originating request came from an async process (at least today) and the persistence key appears to be blank 100% of the time (as of today - 3/24/2017)._ 

HTH!
Sean

**Comment by rappen** [comment]
Thank! That was really interesting info, which I obviously didn't know.
I could of course add these fields too, but I think they will default to not visible (as too many GUIDs hurt my eyes)
👍

**Comment by seanmcne** [comment]
Yeah if there's just a way to see them and sort/find, that would just help with trying to piece things together 😀

**Comment by rappen** [comment]
Available in next release!

![image](https://cloud.githubusercontent.com/assets/2572253/24343628/c6eb39d8-12c7-11e7-9aa2-650ee5ddac5e.png)
