### ISSUE TITLE
Fix Placement of Units

### ISSUE THREAD

**Issue by daryllabar** [Innofactor/XrmToolBox.PluginTraceViewer#51]
![image](https://cloud.githubusercontent.com/assets/9728423/24658045/8ca0db0c-1916-11e7-9b10-683943728f92.png)

In this image, you can see "Exec. Time / Day (s)" in the label.  At first glance this is read as "Execution time per days".  

Recommend changing to "Exec. Time (s/day)" as I am assuming, your units are seconds per day.

**Comment by rappen** [comment]
That is one way of looking at it, definitely.
Or the way I originally thought: "Execution time per day (measured in seconds)".
But I see your point!

**Comment by daryllabar** [comment]
So... 
Execution time per day in seconds, or 
Execution time in seconds per day
idk...

**Comment by craigseymour** [comment]
Or "Cumulative Total of all time spent today executing this plugin(s)", but written in a really narrow font to fit it in :-)

**Comment by craigseymour** [comment]
Or, if we have to be sensible:
"Exec. Time per Day (s)"

Or "Tot.Exec.Time Today (s)"
Or "Total Today (s)" (with the context expressing the total of what!) Perhaps with a tooltip.  (Are those still a thing?)

**Comment by rappen** [comment]
Tooltips are still things. Sort of. You can't touch them. But they are there.
I guess there should be a big tooltip saying:

Execution time per day is calculated using the formula:
```
     Execution Count x Average Execution Time
t = ------------------------------------------
      (Last executed - First executed) x 1000
```
