### ISSUE TITLE
Unable to filter on Date To in the future

### ISSUE THREAD

**Issue by StefanHallberg** [Innofactor/XrmToolBox.PluginTraceViewer#54]
The "date to" field is automatically set to the time for the last log entry when you open the PTV. And by clicking the checkbox for date to, you only receive logs to that exact time. Seems logical.

But:
I wasn´t able to change the time to a later time, although there had been logs created after the intial time.
The work around (or - way to actually do it), which I quite fast saw, was to leave the checkbox unchecked. Maybe it´s obvious, maybe it´s not.....Maybe the "date to" should be able to be changed to a date in the future.

**Comment by seanmcne** [comment]
Having a 'set to now' or not restricting the date would be helpful.  When you open the pane that is the 'latest' date it will allow you to filter on.

**Comment by rappen** [comment]
Duplaces #39 

What would you say about completely removing the constraints? I guess they really don't add much to the usability, and can definitely be annoying in situations as the one you describe here.
