### ISSUE TITLE
Provide Local TMZ option

### ISSUE THREAD

**Issue by daryllabar** [Innofactor/XrmToolBox.PluginTraceViewer#58]
Any chance you can add an option to switch to Local time for entering the time, or, maybe something like this:

![image](https://user-images.githubusercontent.com/9728423/29975311-dfa032a4-8f03-11e7-9128-e2fec610a35f.png)

**Comment by rappen** [comment]
Good idea, thanks @daryllabar . Could you try the attached version?

[PTV#58.zip](https://github.com/Innofactor/XrmToolBox.PluginTraceViewer/files/1274264/PTV.58.zip)

This new option should affect both filter and the Start Time column in the grid.

![image](https://user-images.githubusercontent.com/2572253/30020741-3f41e3fc-9165-11e7-83cd-4ca819fa97ad.png)

**Comment by rappen** [comment]
Or is this when you pay me back for my non existing feedback on https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/74 ...? ;-)

**Comment by daryllabar** [comment]
Or maybe Monday was a holiday for a country you're not in...

**Comment by daryllabar** [comment]
Looks good!  Version number is messed up 9.999, but I'm assuming that's on purpose.

**Comment by rappen** [comment]
Thanks @daryllabar, yes version intentionally "unofficial".
Hope you enjoyed the holiday.

**Comment by rappen** [comment]
Closed with #63
