### ISSUE TITLE
Plugin Trace Viewer - issue opening Plug-in Trace log form when not already logged in.

### ISSUE THREAD

**Issue by JimDaly** [Innofactor/XrmToolBox.PluginTraceViewer#67]
First time to use this tool. 
When I click on any of the rows it seemed to try and open a window. 
I figured out that it is trying to open the Plug-in Trace log form in the application.

But in my case, I’m not logged in to windows using the Microsoft account I use to access CRM Online, so it routes me to log in and then throws an error saying it received a bad request.
_I use a separate incognito (private) browser window when I access my instances._

I got it to work by logging in in my default browser window with my alternate Microsoft account. When doing so, I noticed that this is the URL used:

`https://myorg.crm.dynamics.com//main.aspx?etn=plugintracelog&pagetype=entityrecord&id=260bde8c-92d2-4ee7-896b-b472fa5d9586`

I believe that if the URL could be formatted without `//` it would work as expected even when the user needs to log in.
`https://myorg.crm.dynamics.com/main.aspx?etn=plugintracelog&pagetype=entityrecord&id=260bde8c-92d2-4ee7-896b-b472fa5d9586`

**Comment by rappen** [comment]
Are you sure you are not double-clicking the row? Double-click will open that record in CRM.
Single-click should not try to open anything.

I will though see what I can to do fix the double slash bug.

**Comment by JimDaly** [comment]
Yes, I meant I was double clicking

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
