### ISSUE TITLE
auto refresh 

### ISSUE THREAD

**Issue by aappddeevv** [Innofactor/XrmToolBox.PluginTraceViewer#68]
It would be nice to have an auto refresh mechanism. It probably needs to poll, so it would be nice to set the refresh interval. That way, I can always see the latest trace log without needing to manually refresh.

**Comment by rappen** [comment]
Just so I don't misunderstand, you want to automate the ``F5`` button function, so that the grid with logs records is refreshed every x seconds / when a change is detected?

**Comment by aappddeevv** [comment]
Every x seconds would be fine. I don't think you can detect a change w/o polling anyway so the interval is probably the best way.
