### ISSUE TITLE
Add a Date from Now Button

### ISSUE THREAD

**Issue by daryllabar** [Innofactor/XrmToolBox.PluginTraceViewer#69]
Frequently I'm going to perform a test in an env, after deploying code.  It would be nice to have a "Date From Now" button (or even clicking the Date From Label, that would do a query against CRM to get it's current time (basically the most recent log file would work) and bring that back as the Date From

**Comment by rappen** [comment]
You mean to only show the very most recent logs?
You could just skip date constraints, and reduce record count to return.
No?

**Comment by daryllabar** [comment]
No... Let's say I'm in a very active Dev Environment.  I just pushed a plugin to the environment, and before I start testing, I want to make sure I don't pull in older trace logs in.  So basically just a way to default the from to be "now" (although I'm worried about time differences between the client and the server)

**Comment by rappen** [comment]
Did you try this option?

![image](https://user-images.githubusercontent.com/2572253/36411369-99defbda-1615-11e8-9b57-4b48ba11db88.png)

Should set time constraints according to available log records.

I've never seen it as a problem though, as it always shows latest on top.

**Comment by daryllabar** [comment]
I Just want an easy way to default Date From to now.  The calendar "today" button, doesn't default the Hours or minutes.

**Comment by rappen** [comment]
Available in next release:
https://www.screencast.com/t/UMRgwQkySe
