### ISSUE TITLE
Error refreshing logs

### ISSUE THREAD

**Issue by glosrob** [Innofactor/XrmToolBox.PluginTraceViewer#70]
This has only started today. When refreshing the trace viewer, I get a series of these message boxes:

![image](https://user-images.githubusercontent.com/2010333/36486698-021ccaf4-1717-11e8-9602-1826a3e88460.png)

It is one per column I think (per row).

This is connected to a Dynamics 365 online v8.2 and v9. 

Possibly related - I reported an issue with plugins not updating/being cached (https://community.dynamics.com/crm/f/117/t/268861/) so I don't know if MS are investigating/playing around and that is causing issues.

**Comment by rappen** [comment]
I have noticed that some MS plugins provided with their "apps" produce trace log records that have null in some attributes, which seems very very strange and obvious that they are not practicing what they preach when writing to the log. I have reported this as a bug, which was closed as designed.
Some scenarios should be handled though by PTV, which version are you running?

**Comment by glosrob** [comment]
Noticed these today

![image](https://user-images.githubusercontent.com/2010333/36545538-09ccfe16-17e1-11e8-873a-c6289ccbeab2.png)

Empty columns maybe?

Version of XRM 1.2017.10.19
PTV is 1.2017.12.3

**Comment by rappen** [comment]
Exactly what I was talking about :)
Try latest version 1.2018.2.3, I'm really interested if the problem persists!

**Comment by glosrob** [comment]
Somewhat oddly, the problem seems to have gone this morning (I haven't updated either). Given the general caching/plugin problems we are having (see my link) - I'm not sure what to make of it. I'll monitor to see if it reappears.

**Comment by rappen** [comment]
Closing the issue, feel free to reopen if the problem comes back.
